[tool.poetry]
name = "fastvector"
version = "0.0.1"
description = "Simple, light weight embedding making light weight alternative to Huggingface transformers"
authors = ["NirantK <nirant.bits@gmail.com>"]
license = "Apache License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
qdrant-client = "^1.3.1"
onnxruntime = "^1.15.1"
onnxruntime-silicon = "^1.15.0"
black = "^23.7.0"
ruff = "^0.0.277"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
