[tool.poetry]
name = "fastvector"
version = "0.0.1"
description = "Fast embedding alternative to Sentence transformers"
authors = ["NirantK <nirant.bits@gmail.com>"]
license = "Apache License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
qdrant-client = "^1.3.1"
onnxruntime = "^1.15.1"
sentence-transformers = "^2.2.2"

[tool.poetry.dev-dependencies]
ruff = "^0.0.277"
isort = "^5.12.0"
black = "^23.7.0"
pre-commit = "^3.3.3"

[tool.poetry.dependencies.onnxruntime-silicon]
version = "^1.15.0"
markers = "sys_platform == 'darwin'"  # This makes it macOS specific

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
